FROM ghcr.io/foundry-rs/foundry

WORKDIR /app

COPY . ./optimism

RUN apk update && apk upgrade && apk add curl git nodejs npm jq

RUN npm install -g yarn

RUN cd /app/optimism \
    && yarn install \
    && yarn build \
    && mv /app/optimism/packages/contracts-bedrock/* /app \
    && rm -fr /app/optimism
