FROM node:18.15.0-slim

WORKDIR /app

COPY . ./optimism

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install curl git -y

RUN npm install -g pnpm \
    && pnpm install \
    && mv /app/optimism/packages/contracts-bedrock/* /app \
    && rm -fr /app/optimism
